version: '3.9' # optional since v1.27.0
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: node_container
    command: npm run start:dev
    volumes:
      - ./src:/usr/src/app/src/

    ports:
      - '${PORT}:${PORT}'
    restart: always
    depends_on:
      - postgres
    networks:
      - node-service_network

  # volumes:
  #   - ./:/usr/src/app/
  #   - /usr/src/app/node_modules

  postgres:
    image: postgres:14.4-alpine
    container_name: postgres_container
    volumes:
      - postgres:/data/postgres
    restart: always
    #     build: ./db

    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'

    networks:
      - node-service_network

networks:
  node-service_network:
    driver: bridge
volumes:
  postgres:
